# Generated by Django 5.2.8 on 2025-11-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('telegram_message_id', models.IntegerField()),
                ('received_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'codes',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('type', models.CharField(default='Series', max_length=50)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='ShowDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(null=True)),
                ('episode_number', models.IntegerField(null=True)),
                ('duration_seconds', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show')),
            ],
            options={
                'db_table': 'show_durations',
                'indexes': [models.Index(fields=['show', 'season_number', 'episode_number'], name='idx_duration')],
                'unique_together': {('show', 'season_number', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField()),
                ('season_number', models.IntegerField(default=0)),
                ('episode_number', models.IntegerField(default=0)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show')),
            ],
            options={
                'db_table': 'view_history',
                'indexes': [models.Index(fields=['show', 'view_date', 'season_number', 'episode_number'], name='idx_view')],
                'unique_together': {('show', 'view_date', 'season_number', 'episode_number')},
            },
        ),
    ]
