# Generated by Django 5.2.8 on 2025-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
