# Generated by Django 5.2.8 on 2025-11-13 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Code', 'verbose_name_plural': 'Codes'},
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterModelOptions(
            name='showduration',
            options={'verbose_name': 'Show duration', 'verbose_name_plural': 'Show durations'},
        ),
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name': 'View history record', 'verbose_name_plural': 'View history records'},
        ),
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='showduration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showduration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='code',
            table=None,
        ),
        migrations.AlterModelTable(
            name='logentry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='show',
            table=None,
        ),
        migrations.AlterModelTable(
            name='showduration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='viewhistory',
            table=None,
        ),
    ]
