# Generated by Django 5.2.8 on 2025-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_country_genre_person_show_imdb_rating_show_imdb_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Log entry',
                'verbose_name_plural': 'Log entries',
            },
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='showduration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
