# Generated by Django 5.2.8 on 2025-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_logentry_options_remove_logentry_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'verbose_name': 'View User',
                'verbose_name_plural': 'View Users',
            },
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='history', to='app.viewuser'),
        ),
        migrations.CreateModel(
            name='ViewUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='groups', to='app.viewuser')),
            ],
            options={
                'verbose_name': 'View User Group',
                'verbose_name_plural': 'View User Groups',
            },
        ),
    ]
