# Generated by Django 5.2.8 on 2025-11-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_viewuser_viewhistory_users_viewusergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'rating',
                    models.FloatField(
                        choices=[
                            (0.0, '0.0'),
                            (0.5, '0.5'),
                            (1.0, '1.0'),
                            (1.5, '1.5'),
                            (2.0, '2.0'),
                            (2.5, '2.5'),
                            (3.0, '3.0'),
                            (3.5, '3.5'),
                            (4.0, '4.0'),
                            (4.5, '4.5'),
                            (5.0, '5.0'),
                            (5.5, '5.5'),
                            (6.0, '6.0'),
                            (6.5, '6.5'),
                            (7.0, '7.0'),
                            (7.5, '7.5'),
                            (8.0, '8.0'),
                            (8.5, '8.5'),
                            (9.0, '9.0'),
                            (9.5, '9.5'),
                            (10.0, '10.0'),
                        ]
                    ),
                ),
                (
                    'show',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ratings',
                        to='app.show',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ratings',
                        to='app.viewuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'indexes': [
                    models.Index(fields=['user', 'show'], name='app_userrat_user_id_fe18e3_idx')
                ],
                'unique_together': {('user', 'show')},
            },
        ),
    ]
