# Generated by Django 5.2.8 on 2025-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
