# Generated by Django 5.2.8 on 2025-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='status',
            field=models.CharField(
                choices=[
                    ('QUEUED', 'В очереди'),
                    ('RUNNING', 'Выполняется'),
                    ('SUCCESS', 'Успешно'),
                    ('FAILURE', 'Ошибка'),
                    ('STOPPED', 'Остановлено'),
                ],
                default='QUEUED',
                max_length=20,
            ),
        ),
    ]
