# Generated by Django 5.2.8 on 2025-12-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.constants


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_taskrun_celery_task_id_alter_taskrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuser',
            name='django_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='view_user',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='viewuser',
            name='role',
            field=models.CharField(
                choices=[('guest', 'GUEST'), ('viewer', 'VIEWER'), ('admin', 'ADMIN')],
                default=app.constants.UserRole['GUEST'],
                max_length=20,
            ),
        ),
    ]
