# Generated by Django 5.2.9 on 2025-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_viewuser_django_user_viewuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuser',
            name='role_message_id',
            field=models.IntegerField(
                blank=True, help_text='ID сообщения в админ-канале для управления ролью', null=True
            ),
        ),
    ]
