# Generated by Django 5.2.9 on 2025-12-04 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0012_viewuser_role_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewuser',
            options={'verbose_name': 'Base model', 'verbose_name_plural': 'Base models'},
        ),
        migrations.AlterField(
            model_name='viewuser',
            name='django_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='view_user',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
