# Generated by Django 5.2.9 on 2025-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0013_alter_viewuser_options_alter_viewuser_django_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewuser',
            options={'verbose_name': 'View User', 'verbose_name_plural': 'View Users'},
        ),
        migrations.AddField(
            model_name='viewuser',
            name='is_bot_blocked',
            field=models.BooleanField(default=False, verbose_name='Bot Blocked'),
        ),
    ]
