# Generated by Django 5.2.9 on 2025-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0014_alter_viewuser_options_viewuser_is_bot_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewuser',
            name='is_bot_blocked',
        ),
        migrations.AddField(
            model_name='viewuser',
            name='is_bot_active',
            field=models.BooleanField(default=True, verbose_name='Bot Active'),
        ),
    ]
