# Generated by Django 5.2.9 on 2025-12-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_viewuser_is_bot_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='emoji_flag',
            field=models.CharField(blank=True, help_text='Emoji flag', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code', max_length=2, null=True),
        ),
    ]
