# Generated by Django 5.2.8 on 2025-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0016_country_emoji_flag_country_iso_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='is_checked',
            field=models.BooleanField(default=True, verbose_name='Учтено'),
        ),
    ]
