# Generated by Django 5.2.9 on 2025-12-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0017_viewhistory_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
