# Generated by Django 5.2.8 on 2025-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_viewhistory_telegram_message_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrating',
            name='app_userrat_user_id_fe18e3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrating',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='season_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'show', 'season_number', 'episode_number')},
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user', 'show', 'season_number', 'episode_number'], name='app_userrat_user_id_22de90_idx'),
        ),
    ]
