# Generated by Django 5.2.9 on 2025-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0020_alter_userrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'direction',
                    models.CharField(
                        choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3
                    ),
                ),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Telegram Log',
                'verbose_name_plural': 'Telegram Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['chat_id', 'message_id'], name='app_telegra_chat_id_b7c5e8_idx'
                    ),
                    models.Index(fields=['created_at'], name='app_telegra_created_58f2e0_idx'),
                ],
            },
        ),
    ]
