# Generated by Django 5.2.9 on 2025-12-23 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0021_telegramlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramlog',
            name='app_telegra_chat_id_b7c5e8_idx',
        ),
        migrations.RemoveField(
            model_name='telegramlog',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='telegramlog',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='telegramlog',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='telegramlog',
            name='text',
        ),
    ]
