# Generated by Django 5.2.9 on 2025-12-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0022_remove_telegramlog_app_telegra_chat_id_b7c5e8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlog',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Alive'),
        ),
    ]
