# Generated by Django 5.2.9 on 2026-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_telegramlog_is_alive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewuser',
            options={'ordering': ['telegram_id'], 'verbose_name': 'View User', 'verbose_name_plural': 'View Users'},
        ),
        migrations.AddField(
            model_name='logentry',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
