# Generated by Django 5.2.11 on 2026-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0024_alter_viewuser_options_logentry_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
