# Generated by Django 5.2.11 on 2026-02-26 13:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0025_show_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedStat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.CharField(
                        default=uuid.uuid4, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Shared Stat',
                'verbose_name_plural': 'Shared Stats',
            },
        ),
    ]
