# Generated by Django 5.2.11 on 2026-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0026_sharedstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuser',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
