# Generated by Django 5.2.11 on 2026-03-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0027_viewuser_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_photo_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
