# Generated by Django 5.2.12 on 2026-03-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0028_person_is_photo_fetched_person_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRating',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kp', models.FloatField(blank=True, null=True)),
                ('imdb', models.FloatField(blank=True, null=True)),
                ('tmdb', models.FloatField(blank=True, null=True)),
                ('film_critics', models.FloatField(blank=True, null=True)),
                ('russian_film_critics', models.FloatField(blank=True, null=True)),
                ('await_rating', models.FloatField(blank=True, null=True)),
                (
                    'show',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ext_rating',
                        to='app.show',
                    ),
                ),
            ],
            options={
                'verbose_name': 'External Rating',
                'verbose_name_plural': 'External Ratings',
            },
        ),
    ]
