# Generated by Django 5.2.12 on 2026-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0029_externalrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
