# Generated by Django 5.2.12 on 2026-03-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0030_person_en_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCrew',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('en_profession', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'person',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person'),
                ),
                (
                    'show',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show'),
                ),
            ],
            options={
                'verbose_name': 'Show Crew Member',
                'verbose_name_plural': 'Show Crew Members',
                'unique_together': {('show', 'person', 'profession')},
            },
        ),
        migrations.AddField(
            model_name='show',
            name='crew',
            field=models.ManyToManyField(
                blank=True, related_name='shows_as_crew', through='app.ShowCrew', to='app.person'
            ),
        ),
    ]
