# Generated by Django 5.2.12 on 2026-03-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0031_showcrew_show_crew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo_url',
            new_name='tmdb_photo_url',
        ),
        migrations.RemoveField(
            model_name='show',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='show',
            name='directors',
        ),
        migrations.AddField(
            model_name='person',
            name='kp_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
