# Generated by Django 5.2.12 on 2026-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0033_sitemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ignore_collision',
            field=models.BooleanField(
                default=False, verbose_name='Игнорировать коллизию в названии'
            ),
        ),
    ]
