# Generated by Django 5.2.13 on 2026-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0034_show_ignore_collision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showduration',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showduration',
            name='season_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='episode_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='season_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
