# Generated by Django 5.2.13 on 2026-04-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0035_alter_showduration_episode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='master_person',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='aliases',
                to='app.person',
            ),
        ),
    ]
