# Generated by Django 5.2.13 on 2026-04-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0036_person_master_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistFolder',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='wishlist_folders',
                        to='app.viewuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Wishlist Folder',
                'verbose_name_plural': 'Wishlist Folders',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=0)),
                (
                    'folder',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='app.wishlistfolder',
                    ),
                ),
                (
                    'show',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show'),
                ),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['sort_order', '-id'],
                'unique_together': {('folder', 'show')},
            },
        ),
    ]
