# Generated by Django 5.2.13 on 2026-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0037_wishlistfolder_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistfolder',
            name='color',
            field=models.CharField(default='#60a5fa', max_length=20),
        ),
        migrations.AddField(
            model_name='wishlistfolder',
            name='icon',
            field=models.CharField(default='folder', max_length=50),
        ),
    ]
