# Generated by Django 5.2.13 on 2026-05-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0038_wishlistfolder_color_wishlistfolder_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoSpin',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'show',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.show'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='casino_spins',
                        to='app.viewuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Casino Spin',
                'verbose_name_plural': 'Casino Spins',
                'ordering': ['-created_at'],
            },
        ),
    ]
