# Generated by Django 5.2.13 on 2026-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0040_alter_wishlistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuser',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewuser',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
