# Generated by Django 5.2.13 on 2026-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_viewuser_screen_height_viewuser_screen_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='date_precision',
            field=models.CharField(default='exact', max_length=10),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='view_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
