# Generated by Django 5.2.13 on 2026-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0042_viewhistory_date_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='source',
            field=models.CharField(
                choices=[('manual', 'Manual'), ('kinopub', 'KinoPub')],
                db_index=True,
                default='manual',
                max_length=10,
                verbose_name='Источник',
            ),
        ),
    ]
