# Generated by Django 5.2.14 on 2026-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0043_viewhistory_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinospin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
