# Generated by Django 5.2.16 on 2026-07-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0044_casinospin_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutedShowNotification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'show',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='muted_by_users',
                        to='app.show',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='muted_notifications',
                        to='app.viewuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Muted Show Notification',
                'verbose_name_plural': 'Muted Show Notifications',
                'unique_together': {('user', 'show')},
            },
        ),
    ]
