# Generated by Django 5.2.16 on 2026-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_mutedshownotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutedshownotification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
