# Generated by Django 5.2.16 on 2026-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_mutedshownotification_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistfolder',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
