# Generated by Django 5.2.16 on 2026-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_wishlistfolder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuser',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='Анонимный'),
        ),
        migrations.AddField(
            model_name='viewuser',
            name='privacy_choice_made',
            field=models.BooleanField(default=False),
        ),
    ]
