# Generated by Django 5.2.16 on 2026-07-22 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0048_viewuser_is_anonymous_viewuser_privacy_choice_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedPersonPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_url', models.URLField(db_index=True, max_length=500)),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rejected_photos',
                        to='app.person',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Rejected Person Photo',
                'verbose_name_plural': 'Rejected Person Photos',
                'unique_together': {('person', 'photo_url')},
            },
        ),
    ]
