# Generated by Django 5.2.16 on 2026-07-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0050_show_kinopub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
