# Generated by Django 5.2.16 on 2026-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_reset_show_sequence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='showduration',
            name='idx_duration',
        ),
        migrations.RemoveIndex(
            model_name='viewhistory',
            name='idx_view',
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='TMDB ID'),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='en_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_photo_fetched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='kp_photo_url',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_photo_url',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='type',
            field=models.CharField(db_index=True, default='Series', max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='showcrew',
            name='en_profession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='showcrew',
            name='profession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='view_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='casinospin',
            index=models.Index(fields=['user', 'is_deleted', 'created_at'], name='idx_casino_user_deleted'),
        ),
        migrations.AddIndex(
            model_name='mutedshownotification',
            index=models.Index(fields=['user', 'is_active'], name='idx_muted_user_active'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['type', 'year'], name='idx_show_type_year'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['status', 'year'], name='idx_show_status_year'),
        ),
        migrations.AddIndex(
            model_name='showcrew',
            index=models.Index(fields=['profession', 'show'], name='idx_crew_prof_show'),
        ),
        migrations.AddIndex(
            model_name='showcrew',
            index=models.Index(fields=['en_profession', 'show'], name='idx_crew_enprof_show'),
        ),
        migrations.AddIndex(
            model_name='showcrew',
            index=models.Index(fields=['person', 'profession'], name='idx_crew_person_prof'),
        ),
        migrations.AddIndex(
            model_name='showcrew',
            index=models.Index(fields=['person', 'en_profession'], name='idx_crew_person_enprof'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['show', 'season_number', 'episode_number'], name='idx_userrat_show_se_ep'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['show', 'user'], name='idx_userrat_show_user'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['is_checked', 'view_date'], name='idx_view_checked_date'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['folder', 'is_active'], name='idx_wl_folder_active'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['user', 'is_active', 'include_in_stats'], name='idx_wl_user_stats'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['user', 'show', 'is_active'], name='idx_wl_user_show_active'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['show', 'is_active'], name='idx_wl_show_active'),
        ),
    ]
