# Generated by Django 5.2.16 on 2026-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_showduration_idx_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='TMDB ID'),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='IMDb ID'),
        ),
        migrations.AddField(
            model_name='showduration',
            name='is_estimated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Оценочная длительность'),
        ),
    ]
