# Generated by Django 5.2.16 on 2026-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0055_populate_imdb_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcrew',
            name='en_profession',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='showcrew',
            name='profession',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
