# Generated by Django 5.2 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0065_remove_redundant_tmdb_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='tmdb_enrichment_checked_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='TMDB enrichment checked at',
            ),
        ),
    ]
