# Generated by Django 5.2 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0066_show_tmdb_enrichment_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poiskkino_backfill_checked_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='Poiskkino backfill checked at',
            ),
        ),
    ]
