# Generated by Django 5.2.17 on 2026-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0071_show_imdb_rating_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='kinopoisk_rating_available',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    'Poiskkino returned this title and currently publishes '
                    'a KinoPoisk rating for it.'
                ),
                verbose_name='KinoPoisk rating available',
            ),
        ),
    ]
