DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = f'{DATE_FORMAT} H:i:s'
TIME_FORMAT = 'H:i:s'

SHORT_DATE_FORMAT = DATE_FORMAT
SHORT_DATETIME_FORMAT = f'{DATE_FORMAT} H:i:s'

YEAR_MONTH_FORMAT = 'Y-m'
MONTH_DAY_FORMAT = 'm-d'


_DATE_INPUT_FORMAT = '%d.%m.%Y'

TIME_INPUT_FORMATS = [
    '%H:%M',
    '%H:%M:%S',
]

DATETIME_INPUT_FORMATS = [
    f'{_DATE_INPUT_FORMAT} %H:%M:%S',
    f'{_DATE_INPUT_FORMAT} %H:%M',
]

DATE_INPUT_FORMATS = [
    _DATE_INPUT_FORMAT,
]
